<?xml version="1.0"?>
<package format="3">

  <name>wall_follower</name>
  <version>0.0.1</version>

  <description>
    ROS2 Autonomous Wall Following Robot
  </description>

  <maintainer email="example@gmail.com">
    Samrudh
  </maintainer>

  <license>MIT</license>

  <exec_depend>rclpy</exec_depend>
  <exec_depend>geometry_msgs</exec_depend>
  <exec_depend>sensor_msgs</exec_depend>
  <exec_depend>std_msgs</exec_depend>
  <exec_depend>python3-serial</exec_depend>
  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>

</package>
